### ISSUE TITLE
Lists.js returns no traversals

### ISSUE THREAD

**Issue by m-carrasco** [rohanpadhye/travioli#1]
Hi

I installed Travioli following all the instructions.

When i run: 

`osboxes@osboxes:~/Desktop$ travioli/bin/run.sh travioli/test/lists.js` the result is

```
Done! Analyzed 0 activations of 0 functions.
Traversed 0 data structures in 0 functions, across 0 RAECs.
Redundantly traversed 0 data structures in 0 functions, across 0 RAECs.
```
The .travioli folder is attached to this report. 
[.travioli.tar.gz](https://github.com/rohanpadhye/travioli/files/1339358/default.travioli.tar.gz)

I made these changes in order to use the supported NodeJS version:

```
diff --git a/bin/collect_trace.sh b/bin/collect_trace.sh
index a65e7e0..ac7dd47 100755
--- a/bin/collect_trace.sh
+++ b/bin/collect_trace.sh
@@ -4,7 +4,7 @@ TRAVIOLI_DIR="$(dirname $0)/.."
 JALANGI_DIR="$1"
 
 # Set JS runtime
-node="node"
+node="/home/osboxes/Desktop/node-v4.4.0-linux-x64/bin/node"
 
 if [ $# -lt 2 ]; then
   echo "Usage: $0 JALANGI_DIR JS_FILE [ARGS]" >&2
@@ -12,4 +12,4 @@ if [ $# -lt 2 ]; then
 fi
 
 mkdir -p ".travioli"
-node "$JALANGI_DIR/src/js/commands/jalangi.js" --inlineIID --inlineSource --analysis "$JALANGI_DIR/src/js/sample_analyses/ChainedAnalyses.js" --analysis "$JALANGI_DIR/src/js/runtime/SMemory.js" --analysis "$TRAVIOLI_DIR/src/js/LogData.js" "${@:2}"
+$node "$JALANGI_DIR/src/js/commands/jalangi.js" --inlineIID --inlineSource --analysis "$JALANGI_DIR/src/js/sample_analyses/ChainedAnalyses.js" --analysis "$JALANGI_DIR/src/js/runtime/SMemory.js" --analysis "$TRAVIOLI_DIR/src/js/LogData.js" "${@:2}"
diff --git a/bin/run.sh b/bin/run.sh
index 60d416a..34ce981 100755
--- a/bin/run.sh
+++ b/bin/run.sh
@@ -10,7 +10,7 @@ else
 fi
 
 # Set JS runtime
-NODE="node"
+NODE="/home/osboxes/Desktop/node-v4.4.0-linux-x64/bin/node"
 
 $NODE $@ &&
 "$TRAVIOLI_DIR/bin/collect_trace.sh" "$TRAVIOLI_DIR/node_modules/jalangi2" $@ &&
```

**Comment by m-carrasco** [comment]
@rohanpadhye

**Comment by rohanpadhye** [comment]
@m7nu3l : Thanks for pointing this out. It was an issue with the exclude patterns (`test/` is a default exclude pattern so that test driver code is not analyzed). 

I've moved `lists.js` into directory `examples/` to make it more obvious, and enabled configuring exclude patterns via the environment variable `TRAVIOLI_EXCLUDE_PATTERN`.

**Comment by rohanpadhye** [comment]
Seeing your original post, I've also added support for configuring the NodeJS and Python runnables using `NODEJS` and `PYTHON` environment variables to make it easier to choose a runtime.

**Comment by m-carrasco** [comment]
Thanks! Now it's working.
